# Generated by Django 3.1.2 on 2020-12-02 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HelloDjango', '0002_auto_20201201_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricelist',
            old_name='group',
            new_name='сategory',
        ),
    ]
