# Generated by Django 3.1.2 on 2020-12-02 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HelloDjango', '0004_auto_20201202_1158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricelist',
            old_name='category',
            new_name='category_id',
        ),
    ]
