# Generated by Django 3.1.2 on 2020-12-02 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HelloDjango', '0005_auto_20201202_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='category_id',
            field=models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.PROTECT, related_name='pricelists', to='HelloDjango.category', verbose_name='Группа'),
        ),
    ]
