# Generated by Django 3.1.2 on 2020-12-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelloDjango', '0006_auto_20201202_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='option',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Опция'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='slug',
            field=models.SlugField(blank=True, max_length=400, unique=True),
        ),
    ]
