# Generated by Django 3.1.2 on 2020-12-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelloDjango', '0007_auto_20201203_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='name',
            field=models.CharField(max_length=155, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
