# Generated by Django 3.1.2 on 2020-12-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelloDjango', '0008_auto_20201203_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricelist',
            name='name',
        ),
        migrations.RemoveField(
            model_name='pricelist',
            name='slug',
        ),
        migrations.AddField(
            model_name='category',
            name='maxPrice',
            field=models.FloatField(default=0, verbose_name='Максимальная цена'),
        ),
        migrations.AddField(
            model_name='category',
            name='minPrice',
            field=models.FloatField(default=0, verbose_name='Минимальная цена'),
        ),
    ]
